trigger:
- main

pool:
  name: myAgent

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  agentName: 'myAgent'

stages:
- stage: Initialize
  jobs:
    - job: TerraformInit
      pool:
        name: $(agentName)
      steps:
        - checkout: self

        - script: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          displayName: 'Install Azure CLI'

        - script: |
            export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
            export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
            export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
            export ARM_TENANT_ID=$(ARM_TENANT_ID)
            az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          displayName: 'Azure CLI Login'

        - script: |
            curl -sSL https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip -o terraform.zip
            unzip -o terraform.zip
            sudo mv -f terraform /usr/local/bin/terraform
            terraform version
          displayName: 'Install Terraform'

        - script: |
            terraform init
          displayName: 'Terraform Init'
          workingDirectory: 'terraform/environments/test'

- stage: Plan
  dependsOn: Initialize
  jobs:
    - job: TerraformPlan
      pool:
        name: $(agentName)
      steps:
        - script: |
            terraform plan -out=tfplan
          displayName: 'Terraform Plan'
          workingDirectory: 'terraform/environments/test'

- stage: Apply
  dependsOn: Plan
  jobs:
    - job: TerraformApply
      pool:
        name: $(agentName)
      steps:
        - script: |
            terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
          workingDirectory: 'terraform/environments/test'
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
