trigger:
- main

pool:
  name: myAgent

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  agentName: 'myAgent'

stages:
- stage: Initialize
  jobs:
    - job: TerraformInit
      pool:
        name: $(agentName)
      steps:
        - checkout: self

        - task: UseTerraform@0
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - script: |
            terraform init
          displayName: 'Terraform Init'
          workingDirectory: 'terraform/environments/test'

- stage: Plan
  dependsOn: Initialize
  jobs:
    - job: TerraformPlan
      pool:
        name: $(agentName)
      steps:
        - script: |
            terraform plan -out=tfplan
          displayName: 'Terraform Plan'
          workingDirectory: 'terraform/environments/test'

- stage: Apply
  dependsOn: Plan
  jobs:
    - job: TerraformApply
      pool:
        name: $(agentName)
      steps:
        - script: |
            terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
          workingDirectory: 'terraform/environments/test'
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
