trigger: none

pool:
  name: myAgent

variables:
  serviceConnection: 'mySC'
  azureLocation: 'East US 2'
  terraformWorkingDirectory: 'terraform/environments/test'
  storage_account_name: "tfstate1781720245"
  container_name: "tfstate"
  key: "tfstate.azure.proj3"
  agentName: 'myAgent'
  lockID: 'ec5d85c2-a6de-1f28-681d-bc13dbf74811'


stages:
- stage: tfdeploy
  jobs:
    - job: apply
      pool:
        name: $(agentName)
      steps:
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - script: | 
        terraform force-unlock -force $(lockID) displayName: 'Force Unlock State'
      - task: TerraformTaskV4@4
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(terraformWorkingDirectory)
          backendServiceArm: $(serviceConnection)
          backendAzureRmResourceGroupName: 'Azuredevops'
          backendAzureRmStorageAccountName: $(storage_account_name)
          backendAzureRmContainerName: $(container_name)
          backendAzureRmKey: $(key)
      - task: TerraformTaskV4@4
        displayName: Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: $(terraformWorkingDirectory)
          environmentServiceNameAzureRM: $(serviceConnection)
      - task: TerraformTaskV4@4
        displayName: Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: $(terraformWorkingDirectory)
          environmentServiceNameAzureRM: $(serviceConnection)
